(function(){function x(a,b){return-1<a.indexOf(b)?a:-1<a.indexOf("?")?a+"&"+b:a+"?"+b}function U(a){a.removeAttribute("data-iframely-url");a.removeAttribute("data-iframely-loading")}function V(a,b){var c=b&&b.originalElement;if(!c&&a&&"A"===a.nodeName&&(a.textContent||a.innerText))U(a);else{if(B){var d;d=a;for(var e=!1;!e&&d.parentNode;)d=d.parentNode,e=d.className&&0<=d.className.split(" ").indexOf(B);if(d=e&&d){(c=d.parentNode)&&c.removeChild(d);return}}if(b&&b.iframeContainer)d=b.iframeContainer;
else if(d=a,e=C(a))d=e.maxWidthWrapper;e=d.parentNode;c&&("A"===c.nodeName&&(c.textContent||c.innerText))&&(U(a),e.insertBefore(c,d));e.removeChild(d)}}function J(a){a=a.getBoundingClientRect();var b=window.innerHeight||document.documentElement.clientHeight,c=window.innerWidth||document.documentElement.clientWidth;if(0<=a.bottom&&0<=a.right&&a.top<=b&&a.left<=c)return fa;if(a.bottom>=0-b&&a.right>=0-c&&a.top<=b+b&&a.left<=c+c)return W}function X(a){for(var b=0,c=0;c<a.childNodes.length;c++){var d=
a.childNodes[c];d.nodeType===Node.TEXT_NODE?(d=d.textContent||d.innerText,(d=d.replace(/\s|\n/g,""))&&b++):d.nodeType===Node.ELEMENT_NODE&&b++}return b}function C(a,b){var c=a.parentNode;if(c&&!("DIV"!==c.nodeName||2<X(c)||b&&c.getAttribute("class")!==Y)){var d=c.parentNode;if(d&&!("DIV"!==d.nodeName||1<X(d)||b&&d.getAttribute("class")!==Z))return{aspectWrapper:c,maxWidthWrapper:d}}}function ga(a){var b=K(a);a=b.url;var c=b.api_key,b=b.key,d=[];a&&d.push("url="+encodeURIComponent(a));c&&d.push("api_key="+
encodeURIComponent(c));b&&d.push("key="+encodeURIComponent(b));return"/api/thumbnail?"+d.join("&")}function $(a,b){var c=C(a);if(c){var d;if(b.match(/\/api\/iframe\?.+/))d=b.replace(/\/api\/iframe\?.+/,ga(b));else if(b.match(/^(?:https?:)?\/\/[^\/]+\/[a-zA-Z0-9]+(?:\?.*)?$/))d=b.replace(/^((?:https?:)?\/\/[^\/]+\/[a-zA-Z0-9]+)((?:\?.*)?)$/,"$1/thumbnail");else return;var e=document.createElement("div");e.style.position="absolute";e.style.top="0";e.style.width="100%";e.style.height="100%";e.style.backgroundImage=
"url('"+d+"')";e.style.backgroundSize="cover";e.style.backgroundPosition="center";d=c.aspectWrapper.style["padding-top"];var f=c.aspectWrapper.style["padding-bottom"];if(d&&f&&d.match(/^\d+px$/)){var l=document.createElement("div");l.style.left=0;l.style.top="-"+d;l.style.width="100%";l.style.height=0;l.style.position="relative";l.style["padding-bottom"]=f;l.appendChild(e);c.aspectWrapper.appendChild(l)}else c.aspectWrapper.appendChild(e)}}function aa(a){var b=(a=C(a))&&a.aspectWrapper&&1<a.aspectWrapper.childNodes.length&&
a.aspectWrapper.childNodes[1];b&&"DIV"===b.nodeName&&a.aspectWrapper.removeChild(b)}function ha(a,b){setTimeout(function(){ia(a)},b==W?200:0)}function ia(a){function b(){d++;d===c&&(clearTimeout(e),setTimeout(function(){aa(a)},200))}var c=a.hasAttribute("data-direct")?1:2,d=0,e;a.addEventListener?a.addEventListener("load",b):a.attachEvent("onload",b);e=setTimeout(function(){b()},1E4);var f=a.getAttribute("data-iframely-url");f&&(a.removeAttribute("data-iframely-url"),a.removeAttribute("data-iframely-loading"),
a.setAttribute("src",f))}function ja(a,b){var c=a.getAttribute("data-max-width");c&&(b["max-width"]=c);if(b){b.frame_style&&a.setAttribute("data-frame-style",b.frame_style);b.scrolling&&a.setAttribute("scrolling",b.scrolling);var c=a.getAttribute("data-frame-style"),d=C(a);if(d){var e=d.aspectWrapper,f=d.maxWidthWrapper,l=e.clientHeight;a.removeAttribute("style");a.setAttribute("style","top: 0; left: 0; width: 100%; height: 100%; position: absolute; border: 0; "+(c||""));e.removeAttribute("style");
f.removeAttribute("style");e.style.left=0;e.style.width="100%";e.style.height=0;e.style.position="relative";b&&b.height&&b.width&&!b["aspect-ratio"]?(f.style.width=b.width+"px",e.style.height=b.height+"px",e.style["padding-bottom"]=0):(b.height||b["aspect-ratio"]||(e.style["padding-bottom"]="56.25%"),b["aspect-ratio"]?(e.style["padding-bottom"]=Math.round(1E5/b["aspect-ratio"])/1E3+"%",b["padding-bottom"]&&(e.style["padding-top"]=b["padding-bottom"]+"px")):(b.height&&(e.style.height=b.height+"px",
e.style["padding-bottom"]=0),b.width&&(e.style.width=b.width+"px")),(b["max-width"]||b["min-width"])&&["max-width","min-width"].forEach(function(a){var c=b[a];if(c){if("number"===typeof c||"string"===typeof c&&c.match(/^(\d+)?\.?(\d+)?$/))c+="px";f.style[a]=c}}),"undefined"!==typeof checkLazyLoad&&checkLazyLoad());(function(){var b=e.clientHeight;l!=b&&w.trigger("heightChanged",a,l,b)})()}}}function K(a){if(a=a.match(/\?(.+)/i)){a=a[1];a=a.split("&");for(var b={},c=0;c<a.length;c++){var d=a[c].split("=");
b[d[0]]=decodeURIComponent(d[1])}return b}return{}}function ka(){var a=!1;try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")?!0:!1}catch(b){a=navigator.mimeTypes&&void 0!=navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin?!0:!1}return a}var k=window.iframely=window.iframely||{},f=k.widgets=k.widgets||{},w=k.events=k.events||{},y=f._iframes=f._iframes||[],L=f._global_iframes=f._global_iframes||[],n=f._lazy_iframes=f._lazy_iframes||
[],E=f._lazy_widgets=f._lazy_widgets||[],M=f._import_links=f._import_links||{},F,G,N,H,D,B,O,ca,I,P,Q=/^(?:https?:)?\/\/[^\/]+/,la=/^(?:https?:)?\/\/[^\/]+\/(\w+)(?:\?.*)?$/;f.load||(k.load=f.load=function(){if(0===arguments.length){var a=document.querySelectorAll("[data-iframely-url]"),b;if(!(-1<navigator.userAgent.toLowerCase().indexOf("firefox"))&&1<a.length&&"file:"!==document.location.protocol&&"import"in(b=document.createElement("link"))){for(var c=[],d=[],e={},v,l,s,g,p,h,n,k,u=function(a,
b){e[a]||(e[a]=[]);e[a].push(b)},x=function(){for(var a in e)for(var b=e[a],c=0;c<b.length;c++){var d=b[c];"import"===d.getAttribute("data-iframely-loading")&&(d.removeAttribute("data-iframely-loading"),f.createWidget(d))}},z=0;z<a.length;z++){var m=a[z];if(!m.getAttribute("data-iframely-loading")){var q=m.getAttribute("data-iframely-url");v=(v=q.match(Q))&&v[0]||D;var A=q.match(la),A=A&&A[1],w;g=g||q.match(/align=left/);p=p||(w=q.match(/iframe=([\w-]+)/))&&w[1];h=h||q.match(/autoplay=(true|1)/);
k=k||q.match(/playerjs=(true|1)/);var y=q.match(/maxwidth=(\d+)/);y&&(n=n||y[1]);A?(m.setAttribute("data-iframely-loading","import"),-1===d.indexOf(A)&&d.push(A),u(A,m)):(s=K(q),(q=s.url)||(q=m.getAttribute("href")),l=s.api_key||F,s=s.key||G,(l||s)&&q?(m.setAttribute("data-iframely-loading","import"),-1===c.indexOf(q)&&c.push(q),u(q,m)):f.createWidget(m))}}if((0<c.length||0<d.length)&&v){b.rel="import";b.href=v+"/api/import?app=1";ka()?b.href+="&flash=1":b.href+="&flash=0";0<c.length&&(c=c.map(function(a){return"uri="+
encodeURIComponent(a)}),b.href+="&"+c.join("&"));0<d.length&&(b.href+="&ids="+encodeURIComponent(d.join("&")));l?b.href+="&api_key="+l:s&&(b.href+="&key="+s);if(g||"left"===I)b.href+="&align=left";if(p||P)b.href+="&iframe="+(p||P);h&&(b.href+="&autoplay=1");if(n||H)b.href+="&maxwidth="+(n||H);if(k||ca)b.href+="&playerjs=1";var B=function(a){for(var b=(a=a["import"])?a.querySelectorAll("template[data-uri]"):[],c=0;c<b.length;c++){var d=b[c],h=d.getAttribute("data-iframe-src"),l=d.hasAttribute("data-cancel"),
v=d.hasAttribute("data-shadow"),g=d.getAttribute("data-uri"),q=d.hasAttribute("data-render-event"),s=e[g];if(s){for(var n=0;n<s.length;n++){var r=s[n];if(l)V(r);else if(h)r.removeAttribute("data-iframely-loading"),f.createWidget(r,{directIframeSrc:h});else{var p=document.importNode(d.content,!0),k,m,t=!q&&C(r,!0);t?(k=t.aspectWrapper.parentNode,m=t.aspectWrapper,t.maxWidthWrapper.removeAttribute("style")):(k=r.parentNode,m=r);var u=O||r.hasAttribute("data-lazy");if("IFRAME"===r.nodeName)r.removeAttribute("data-iframely-loading"),
f.createWidget(r);else{if(v){var ba=document.createElement("div"),w=ba.createShadowRoot();w.appendChild(p);f.applyCardStyles&&f.applyCardStyles({shadowRoot:w,container:k,sourceTemplate:d,importDoc:a});p=ba}!u||J(r)?(k.insertBefore(p,m),k.removeChild(m)):(t?(t=m,r.parentNode.removeChild(r)):(t=document.createElement("div"),k.insertBefore(t,m),k.removeChild(m),t.style.width="100%",t.style.height="400px"),E.push({container:t,widget:p}))}}}delete e[g]}}x()};b.onload=function(){B(b)};b.onerror=function(){x()};
b.href in M?B(M[b.href]):(M[b.href]=b,document.head.appendChild(b))}}else for(z=0;z<a.length;z++)m=a[z],f.createWidget(m)}else 1===arguments.length?f.createWidget(arguments[0]):2===arguments.length&&f.createWidgetInContainer(arguments[0],arguments[1])});f.createWidgetInContainer||(f.createWidgetInContainer=function(a,b){var c=document.createElement("a");c.setAttribute("href",b);c.textContent=b;a.appendChild(c);f.createWidget(c)});f.createWidget||(f.createWidget=function(a,b){if(!a.getAttribute("data-iframely-loading")){a.setAttribute("data-iframely-loading",
!0);var c=a.getAttribute("data-iframely-url"),d=a.hasAttribute("data-img"),e=c&&c.match(/^((?:https?:)?\/\/[^\/]+)\/\w+/i),e=e&&e[1],v=O||a.hasAttribute("data-lazy")||"IFRAME"===a.nodeName;if("IFRAME"===a.nodeName)b&&b.directIframeSrc&&a.setAttribute("data-direct",""),v?(d&&($(a,c),c=x(c,"img=1")),a.setAttribute("data-iframely-url",b&&b.directIframeSrc||c),n.push({iframe:a})):(a.setAttribute("src",b&&b.directIframeSrc||c),a.removeAttribute("data-iframely-url"),a.removeAttribute("data-iframely-loading")),
y.push({iframe:a});else{var l=a.getAttribute("href"),k,g=C(a);k=g&&g.maxWidthWrapper?g.maxWidthWrapper.parentNode:a.parentNode;var p=a.getAttribute("data-max-width"),h;!l||c&&e?c&&(h=x(c,"app=1"),"auto"===p&&(c=k.clientWidth)&&(h=x(h,"maxwidth="+c)),I&&(h=x(h,"align="+I))):(p=p||H,h="/api/iframe?app=1&url="+encodeURIComponent(l),h=G?D+h+"&key="+G:F?D+h+"&api_key="+F:"http://open.iframe.ly"+h,N&&(h+="&"+N));h&&(e=h.match(/^(https?:)?\/\//i),e[1]||"file:"!==document.location.protocol||(h="http:"+h),
g?(c=g.maxWidthWrapper,g.aspectWrapper.innerHTML='<iframe allowfullscreen style="top: 0; width: 100%; height: 100%; position: absolute; border: 0;"></iframe>'):(c=document.createElement("div"),c.innerHTML='<div style="width: 100%; position: relative; padding-bottom: 56.25%;"><iframe allowfullscreen style="top: 0; width: 100%; height: 100%; position: absolute; border: 0;"></iframe></div>'),e=c.querySelector("iframe"),p&&parseInt(p)&&(c.setAttribute("style","max-width: "+p+"px;"),e.setAttribute("data-max-width",
p)),y.push({iframe:e,iframeContainer:c,originalElement:a}),g||(k.insertBefore(c,a),k.removeChild(a)),v?(d&&($(e,h),h=x(h,"img=1")),e.setAttribute("data-iframely-url",h),e.setAttribute("data-iframely-loading",!0),n.push({iframe:e})):e.setAttribute("src",h))}f.checkLazyLoad()}});var Y="iframely-responsive",Z="iframely-embed";f.importedWidgetRendered||(f.importedWidgetRendered=function(a){a=a.parentNode;for(var b=1;a&&a.getAttribute("class")!==Y;)a=a.parentNode,b++,4<b&&(a=null);(b=a&&a.parentNode)&&
b.getAttribute("class")===Z&&(a.removeAttribute("style"),a.removeAttribute("class"),b.removeAttribute("style"))});if(!w.on){var R={};w.on=function(a,b){(R[a]=R[a]||[]).push(b)};w.trigger=function(a){var b=Array.prototype.slice.call(arguments,1),c=R[a]||[];c.forEach(function(a){a.apply(c,b)})}}f.ready||(f.ready=function(a){"function"===typeof a&&a()});for(var k=function(){return{postMessage:function(a,b,c){a=JSON.stringify(a);c=c||window.parent;window.postMessage&&c.postMessage(a,(b||"*").replace(/([^:]+:\/\/[^\/]+).*/,
"$1"))},receiveMessage:function(a){function b(b){var d;try{d=JSON.parse(b.data)}catch(e){}a(b,d)}if(window.postMessage)if(window.addEventListener)window[a?"addEventListener":"removeEventListener"]("message",b,!1);else window[a?"attachEvent":"detachEvent"]("onmessage",b)}}}(),da=document.querySelectorAll("script"),S=0;S<da.length&&!D;S++){var u=da[S].getAttribute("src");if(u&&u.match(/\/embed\.js/)){var g=K(u);F=g.api_key;G=g.key;H=g.maxwidth;B=g.parent;O=g.lazy;ca=g.playerjs;I=g.align;P=g.iframe;
delete g.api_key;delete g.key;var ea=[],T;for(T in g)ea.push(T+"="+encodeURIComponent(g[T]));N=ea.join("&");D=(u=u.match(Q)||document.location.href.match(Q))&&u[0]||"https://iframe.ly"}}f.checkLazyLoad||(f._checkLazyLoad=function(){f.checkLazyLoadTimeout&&clearTimeout(f.checkLazyLoadTimeout);f.checkLazyLoadTimeout=null;for(var a=0;a<n.length;){var b=n[a].iframe,c=J(b);c?(n.splice(a,1),ha(b,c)):a++}for(a=0;a<E.length;)b=E[a],(c=J(b.container))?(E.splice(a,1),c=b,b=c.container.parentNode,b.insertBefore(c.widget,
c.container),b.removeChild(c.container)):a++},f.checkLazyLoad=function(){f.checkLazyLoadTimeout||(f.checkLazyLoadTimeout=setTimeout(f._checkLazyLoad,300))},window.addEventListener?(addEventListener("scroll",f.checkLazyLoad,!0),addEventListener("resize",f.checkLazyLoad,!0)):window.attachEvent&&(attachEvent("onscroll",f.checkLazyLoad),attachEvent("onresize",f.checkLazyLoad)));f.receiveMessageRegistered||(f.receiveMessageRegistered=!0,k.receiveMessage(function(a,b){if(b&&b.method){for(var c=null,d=null,
e=0;e<y.length&&!c;e++){var f=y[e];f.iframe.contentWindow===a.source&&(c=f.iframe,d=f)}if(!c)for(e=0;e<L.length&&!c;e++)f=L[e],f.contentWindow===a.source&&(c=f);if(!c)for(var g=document.querySelectorAll("iframe"),e=0;e<g.length&&!c;e++)f=g[e],f.contentWindow===a.source&&(L.push(f),c=f);if(c&&"widgetRendered"===b.method){for(e=0;e<n.length;)f=n[e].iframe,c===f?n.splice(e,1):e++;aa(c)}!c||"setIframelyWidgetSize"!==b.method&&"resize"!==b.method&&"setIframelyEmbedData"!==b.method||ja(c,b.data&&b.data.media||
{height:b.height});c&&"cancelWidget"===b.method&&V(c,d)}}));var fa=1,W=2;(function(a){"complete"!==document.readyState&&"interactive"!==document.readyState||a();document.addEventListener?document.addEventListener("DOMContentLoaded",a):window.attachEvent("onload",a)})(function(){f.load()});(f._e||[]).forEach(function(a){"function"===typeof a&&a()})})();
